# Lab 4 — NumPy: Arrays and Vectors
**ARTI 303 — Programming for AI**

**Name:** _rima al shawyah_  **Student ID:** _225002150_  **Section:** _Ai01_

---

### Why this lab exists

Python lists are flexible and slow. That's a fine trade when you have
twenty items. It stops being fine at twenty million.

Almost every AI and data library you will ever touch is built on
**NumPy** arrays underneath. Learning NumPy isn't learning one more
library — it's learning the shape of everything that comes after it.

More than speed, though, this lab is about a different way of writing
code. You'll stop writing "for each item, do something" and start
writing "do this to the whole array." That shift is the point.

### Setup

NumPy isn't part of Python's standard library, so it has to be
installed and recorded:

```bash
python -m pip install numpy
python -m pip freeze > requirements.txt
```

Run both. The second one matters as much as the first — an installed
package that isn't in `requirements.txt` doesn't exist as far as anyone
else's machine is concerned.



In [57]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.5.3


`import numpy as np` — `np` is the universal convention. Every NumPy
example you find online will use it, so use it too.

### Confirm it's recorded

In [58]:
import os

if os.path.exists("requirements.txt"):
    contents = open("requirements.txt").read()
    print(contents)
    if "numpy" in contents.lower():
        print("numpy is recorded.")
    else:
        print("numpy is NOT in requirements.txt - run pip freeze again.")
else:
    print("No requirements.txt here yet.")
    print("Run: python -m pip freeze > requirements.txt")

No requirements.txt here yet.
Run: python -m pip freeze > requirements.txt


---
# Part 1 · Why arrays instead of lists

Let's measure the difference rather than assert it.

In [3]:
import time

size = 1_000_000
py_list = list(range(size))
np_array = np.arange(size)

# Doubling every value with a Python loop
start = time.time()
doubled_list = [x * 2 for x in py_list]
list_time = time.time() - start

# The same thing with NumPy
start = time.time()
doubled_array = np_array * 2
array_time = time.time() - start

print(f"Python list: {list_time:.4f} seconds")
print(f"NumPy array: {array_time:.4f} seconds")
print(f"NumPy is about {list_time / array_time:.0f}x faster here")

Python list: 0.0757 seconds
NumPy array: 0.0036 seconds
NumPy is about 21x faster here


Same result, very different cost. Two reasons:

1. **One type, packed together.** A list can hold anything, so Python
   stores a pointer to each item scattered in memory. A NumPy array
   holds one type in one contiguous block.
2. **The loop runs in C, not Python.** `np_array * 2` hands the whole
   operation to compiled code instead of stepping through a Python loop
   a million times.

Notice what the NumPy version looks like:

```python
doubled_array = np_array * 2
```

No loop at all. That's **vectorisation** — describing the operation on
the whole array and letting NumPy handle the iteration.

---
# Part 2 · Creating arrays

From a list you already have:

In [4]:
gpas = np.array([4.60, 3.90, 4.85, 4.40, 2.95])

print(gpas)
print("type: ", type(gpas))
print("dtype:", gpas.dtype)      # what's inside
print("shape:", gpas.shape)      # dimensions
print("size: ", gpas.size)       # total elements

[4.6  3.9  4.85 4.4  2.95]
type:  <class 'numpy.ndarray'>
dtype: float64
shape: (5,)
size:  5


Three attributes you'll check constantly:

| Attribute | Means |
|---|---|
| `dtype` | the type of every element (`float64`, `int64`, `bool`, ...) |
| `shape` | a tuple of dimensions — `(5,)` is 5 elements in one dimension |
| `size` | total number of elements |

`shape` is the one you'll check most. Most NumPy errors are shape
errors.

### Built-in creators

In [5]:
print("zeros:   ", np.zeros(5))
print("ones:    ", np.ones(3))
print("full:    ", np.full(4, 7.5))
print("arange:  ", np.arange(0, 10, 2))       # start, stop, step
print("linspace:", np.linspace(0, 1, 5))      # start, stop, how many

zeros:    [0. 0. 0. 0. 0.]
ones:     [1. 1. 1.]
full:     [7.5 7.5 7.5 7.5]
arange:   [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


`arange` takes a **step**; `linspace` takes a **count** and spaces the
values evenly. When you need exactly N points across a range, use
`linspace` — it hits both endpoints without floating-point drift.

### Two dimensions

A 2D array is a table: rows and columns.

In [6]:
# 4 students, 3 exams each
scores = np.array([
    [88, 92, 79],
    [75, 68, 82],
    [95, 91, 98],
    [60, 72, 65],
])

print(scores)
print()
print("shape:", scores.shape, "-> 4 rows, 3 columns")
print("ndim: ", scores.ndim, "dimensions")

[[88 92 79]
 [75 68 82]
 [95 91 98]
 [60 72 65]]

shape: (4, 3) -> 4 rows, 3 columns
ndim:  2 dimensions


`shape` reads outermost-first: `(4, 3)` means 4 rows, each with 3
values.

### Exercise 2.1
Create:
- `temps` — a 1D array from the list `[22.5, 24.1, 26.8, 25.3]`
- `zeros_grid` — a 2D array of zeros with 3 rows and 5 columns
- `steps` — 6 evenly spaced values from 0 to 100 inclusive

For `zeros_grid`, `np.zeros()` takes a shape tuple: `np.zeros((rows, cols))`.

In [7]:
temps = np.array([22.5, 24.1, 26.8, 25.3])
zeros_grid = np.zeros((3, 5))
steps = np.linspace(0, 100, 6)

print(temps)
print(zeros_grid)
print(steps)


[22.5 24.1 26.8 25.3]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[  0.  20.  40.  60.  80. 100.]


In [8]:
assert temps is not None and zeros_grid is not None and steps is not None, \
    "fill in every TODO above before running this check"
assert temps.shape == (4,), f"temps shape should be (4,), got {temps.shape}"
assert zeros_grid.shape == (3, 5), f"zeros_grid shape should be (3, 5), got {zeros_grid.shape}"
assert zeros_grid.sum() == 0, "zeros_grid should be all zeros"
assert steps.shape == (6,), f"steps should have 6 values, got {steps.shape}"
assert steps[0] == 0 and steps[-1] == 100, "steps should run from 0 to 100 inclusive"
print("Exercise 2.1 correct.")

Exercise 2.1 correct.


---
# Part 3 · Indexing and slicing

For 1D arrays this works exactly like lists.

In [9]:
gpas = np.array([4.60, 3.90, 4.85, 4.40, 2.95])

print("first:  ", gpas[0])
print("last:   ", gpas[-1])
print("1 to 3: ", gpas[1:4])
print("every 2:", gpas[::2])

first:   4.6
last:    2.95
1 to 3:  [3.9  4.85 4.4 ]
every 2: [4.6  4.85 2.95]


For 2D, you give **two** positions: `array[row, column]`.

In [10]:
scores = np.array([
    [88, 92, 79],
    [75, 68, 82],
    [95, 91, 98],
    [60, 72, 65],
])

print("row 0, col 1: ", scores[0, 1])
print()
print("whole row 2:  ", scores[2])
print("whole col 1:  ", scores[:, 1])      # : means "all rows"
print()
print("first 2 rows, last 2 cols:")
print(scores[:2, 1:])

row 0, col 1:  92

whole row 2:   [95 91 98]
whole col 1:   [92 68 91 72]

first 2 rows, last 2 cols:
[[92 79]
 [68 82]]


`scores[:, 1]` — the colon means "everything in this dimension." That's
how you pull a whole column, and there's no clean equivalent with plain
Python lists.

### Exercise 3.1
From `scores` above, extract:
- `student_2` — all scores for the student at index 2
- `exam_0` — every student's score on exam 0
- `corner` — the last 2 rows and the first 2 columns

In [11]:
student_2 = scores[2]
exam_0 = scores[:, 0]
corner = scores[-2:, :2]

print(student_2)
print(exam_0)
print(corner)


[95 91 98]
[88 75 95 60]
[[95 91]
 [60 72]]


In [12]:
assert student_2 is not None and exam_0 is not None and corner is not None, \
    "fill in every TODO above before running this check"
assert list(student_2) == [95, 91, 98], f"got {student_2}"
assert list(exam_0) == [88, 75, 95, 60], f"got {exam_0}"
assert corner.shape == (2, 2), f"corner shape should be (2, 2), got {corner.shape}"
assert corner.tolist() == [[95, 91], [60, 72]], f"got {corner.tolist()}"
print("Exercise 3.1 correct.")

Exercise 3.1 correct.


---
# Part 4 · Views and copies

This is the part of NumPy that causes silent, hard-to-find bugs. Not
crashes — **wrong numbers, with no error message.**

Slicing a Python list gives you a new list. Slicing a NumPy array gives
you a **view**: a window onto the *same* memory.

In [13]:
# Python list: slicing copies
py = [1, 2, 3, 4, 5]
py_slice = py[1:4]
py_slice[0] = 999
print("list original after editing slice:", py)

list original after editing slice: [1, 2, 3, 4, 5]


In [14]:
# NumPy: slicing does NOT copy
arr = np.array([1, 2, 3, 4, 5])
arr_slice = arr[1:4]
arr_slice[0] = 999
print("array original after editing slice:", arr)

array original after editing slice: [  1 999   3   4   5]


The original array changed. Nothing warned you.

This is deliberate — not copying is what makes NumPy fast on large
data. But it means a function that "just looks at a slice" can quietly
modify your dataset.

### Making a real copy

When you want independence, say so with `.copy()`.

In [15]:
arr = np.array([1, 2, 3, 4, 5])
safe = arr[1:4].copy()
safe[0] = 999

print("original:", arr)
print("copy:    ", safe)

original: [1 2 3 4 5]
copy:     [999   3   4]


Same trap with plain assignment — `b = a` does not copy anything, it
just gives the same array a second name.

In [16]:
a = np.array([1, 2, 3])
b = a              # NOT a copy
c = a.copy()       # a real copy

b[0] = 100
c[1] = 200

print("a:", a)     # changed by b
print("b:", b)
print("c:", c)     # independent

a: [100   2   3]
b: [100   2   3]
c: [  1 200   3]


### Exercise 4.1
`readings` holds sensor data. You need the first three values
**cleaned** (set to 0.0) for a separate calculation — but `readings`
itself must stay untouched.

Create `first_three_clean` as an independent copy, zero it out, and
leave `readings` unchanged.

In [17]:
readings = np.array([21.0, 100.0, 23.5, 22.0, 19.5])

first_three_clean = readings[:3].copy()
first_three_clean[:] = 0.0

print("first_three_clean:", first_three_clean)
print("readings:         ", readings)


first_three_clean: [0. 0. 0.]
readings:          [ 21.  100.   23.5  22.   19.5]


In [18]:
assert first_three_clean is not None, "first_three_clean is still None"
assert list(first_three_clean) == [0.0, 0.0, 0.0], f"got {first_three_clean}"
assert list(readings) == [21.0, 100.0, 23.5, 22.0, 19.5], \
    f"readings should be unchanged - you modified the original: {readings}"
print("Exercise 4.1 correct.")

Exercise 4.1 correct.


> **Rule of thumb:** if a function receives an array and modifies it,
> assume the caller's data changed too, unless you copied first. When a
> value is mysteriously wrong later in a pipeline, this is the first
> thing to check.

---
# Part 5 · Vectorized operations

Arithmetic applies to every element at once.

In [19]:
gpas = np.array([4.60, 3.90, 4.85, 4.40, 2.95])

print("as percent:  ", gpas / 5.0 * 100)
print("plus 0.1:    ", gpas + 0.1)
print("squared:     ", gpas ** 2)
print("rounded:     ", np.round(gpas))

as percent:   [92. 78. 97. 88. 59.]
plus 0.1:     [4.7  4.   4.95 4.5  3.05]
squared:      [21.16   15.21   23.5225 19.36    8.7025]
rounded:      [5. 4. 5. 4. 3.]


Arrays of the same shape combine element by element.

In [20]:
midterm = np.array([80, 65, 92, 55])
final   = np.array([88, 70, 95, 60])

print("difference:", final - midterm)
print("average:   ", (midterm + final) / 2)

difference: [8 5 3 5]
average:    [84.  67.5 93.5 57.5]


### Useful mathematical functions

In [21]:
values = np.array([1.0, 4.0, 9.0, 16.0])

print("sqrt:", np.sqrt(values))
print("log: ", np.log(values))
print("exp: ", np.exp(np.array([0.0, 1.0, 2.0])))
print("abs: ", np.abs(np.array([-3.0, 2.0, -1.0])))

sqrt: [1. 2. 3. 4.]
log:  [0.         1.38629436 2.19722458 2.77258872]
exp:  [1.         2.71828183 7.3890561 ]
abs:  [3. 2. 1.]


### Exercise 5.1
`raw_scores` are out of 100. Convert them to our 5.00 GPA scale and
round to 2 decimal places, storing the result in `gpa_scale`.

A score of 100 maps to 5.00, a score of 0 maps to 0.00.

Do it **without a loop** — one expression.

In [22]:
raw_scores = np.array([88, 65, 97, 55, 72])

gpa_scale = np.round(raw_scores / 100 * 5, 2)

print(gpa_scale)


[4.4  3.25 4.85 2.75 3.6 ]


In [23]:
assert gpa_scale is not None, "gpa_scale is still None"
expected = [4.40, 3.25, 4.85, 2.75, 3.60]
assert np.allclose(gpa_scale, expected), f"expected {expected}, got {list(gpa_scale)}"
print("Exercise 5.1 correct.")

Exercise 5.1 correct.


> `np.allclose` compares floating-point arrays with a small tolerance.
> Use it instead of `==` for floats — `0.1 + 0.2 == 0.3` is `False` in
> every language that uses binary floating point, Python included.

---
# Part 6 · Boolean masks — filtering without loops

Comparing an array to a value gives you an array of `True`/`False`.

In [24]:
gpas = np.array([4.60, 3.90, 4.85, 4.40, 2.95])

mask = gpas >= 4.50
print("mask:", mask)

mask: [ True False  True False False]


That mask can then select elements.

In [25]:
print("Dean's List GPAs:", gpas[gpas >= 4.50])
print("how many:        ", np.sum(gpas >= 4.50))
print("their positions: ", np.where(gpas >= 4.50)[0])

Dean's List GPAs: [4.6  4.85]
how many:         2
their positions:  [0 2]


`np.sum()` on a boolean array counts the `True` values, because `True`
is 1 and `False` is 0. Counting a condition is that short.

### Combining conditions

Use `&` (and), `|` (or), `~` (not) — **not** the words `and`/`or`. And
each condition needs its own brackets.

In [26]:
gpas = np.array([4.60, 3.90, 4.85, 4.40, 2.95])

print("between 3.5 and 4.5:", gpas[(gpas >= 3.50) & (gpas < 4.50)])
print("below 3.5 or above 4.8:", gpas[(gpas < 3.50) | (gpas > 4.80)])
print("NOT Dean's List:", gpas[~(gpas >= 4.50)])

between 3.5 and 4.5: [3.9 4.4]
below 3.5 or above 4.8: [4.85 2.95]
NOT Dean's List: [3.9  4.4  2.95]


### Replacing values conditionally

`np.where(condition, value_if_true, value_if_false)`.

In [27]:
readings = np.array([21.0, 100.0, 23.5, 22.0, 19.5])

# Treat anything above 50 as a sensor fault, replace with the mean of the rest
valid_mean = readings[readings <= 50].mean()
cleaned = np.where(readings > 50, valid_mean, readings)

print("original:", readings)
print("cleaned: ", np.round(cleaned, 2))

original: [ 21.  100.   23.5  22.   19.5]
cleaned:  [21.  21.5 23.5 22.  19.5]


### Exercise 6.1
Using `class_gpas`:
- `dean_list` — the GPAs at or above 4.50
- `at_risk_count` — how many are **below 2.00**
- `capped` — every GPA above 5.00 replaced with 5.00 (data-entry errors), others unchanged

All three without a loop.

In [28]:
class_gpas = np.array([4.60, 1.85, 4.85, 5.40, 2.95, 4.50, 1.20])

dean_list = class_gpas[class_gpas >= 4.50]
at_risk_count = np.sum(class_gpas < 2.00)
capped = np.where(class_gpas > 5.00, 5.00, class_gpas)

print("dean_list:    ", dean_list)
print("at_risk_count:", at_risk_count)
print("capped:       ", capped)


dean_list:     [4.6  4.85 5.4  4.5 ]
at_risk_count: 2
capped:        [4.6  1.85 4.85 5.   2.95 4.5  1.2 ]


In [29]:
assert dean_list is not None and at_risk_count is not None and capped is not None, \
    "fill in every TODO above before running this check"
assert np.allclose(dean_list, [4.60, 4.85, 5.40, 4.50]), f"got {list(dean_list)}"
assert at_risk_count == 2, f"expected 2 at risk, got {at_risk_count}"
assert np.allclose(capped, [4.60, 1.85, 4.85, 5.00, 2.95, 4.50, 1.20]), f"got {list(capped)}"
print("Exercise 6.1 correct.")

Exercise 6.1 correct.


---
# Part 7 · Aggregation and `axis`

Summarising a 1D array is straightforward.

In [30]:
gpas = np.array([4.60, 3.90, 4.85, 4.40, 2.95])

print("sum:   ", gpas.sum())
print("mean:  ", gpas.mean().round(3))
print("min:   ", gpas.min())
print("max:   ", gpas.max())
print("std:   ", gpas.std().round(3))
print("argmax:", gpas.argmax(), "<- position of the highest")

sum:    20.7
mean:   4.14
min:    2.95
max:    4.85
std:    0.672
argmax: 2 <- position of the highest


`argmax` gives the **position**, not the value — useful when you need
to look up who it belongs to.

### `axis` on 2D arrays

This is the concept students most often get backwards, so it's worth
slowing down.

- `axis=0` collapses **rows** → one result per **column**
- `axis=1` collapses **columns** → one result per **row**

Think of it as "the axis that disappears."

`scores` has shape `(4, 3)` — 4 students, 3 exams.

In [31]:
scores = np.array([
    [88, 92, 79],
    [75, 68, 82],
    [95, 91, 98],
    [60, 72, 65],
])

print("overall mean:     ", scores.mean().round(2))
print()
print("axis=0 ->", scores.mean(axis=0).round(2), " shape", scores.mean(axis=0).shape)
print("   one value per EXAM (the 4 students collapsed)")
print()
print("axis=1 ->", scores.mean(axis=1).round(2), " shape", scores.mean(axis=1).shape)
print("   one value per STUDENT (the 3 exams collapsed)")

overall mean:      80.42

axis=0 -> [79.5  80.75 81.  ]  shape (3,)
   one value per EXAM (the 4 students collapsed)

axis=1 -> [86.33 75.   94.67 65.67]  shape (4,)
   one value per STUDENT (the 3 exams collapsed)


Check the shapes: `(4, 3)` with `axis=0` gives `(3,)`, and with
`axis=1` gives `(4,)`. The axis you name is the one that vanishes.

When you're unsure which you want, ask: *how many results do I expect?*
Three exam averages → the answer must have shape `(3,)` → `axis=0`.

### Exercise 7.1
From `scores`:
- `per_student` — each student's average, rounded to 2 decimals
- `per_exam_max` — the highest score on each exam
- `best_student` — the **index** of the student with the highest average
- `hardest_exam` — the **index** of the exam with the lowest average

In [32]:
per_student = np.round(scores.mean(axis=1), 2)
per_exam_max = scores.max(axis=0)
best_student = per_student.argmax()
hardest_exam = scores.mean(axis=0).argmin()

print("per_student: ", per_student)
print("per_exam_max:", per_exam_max)
print("best_student:", best_student)
print("hardest_exam:", hardest_exam)


per_student:  [86.33 75.   94.67 65.67]
per_exam_max: [95 92 98]
best_student: 2
hardest_exam: 0


In [33]:
assert per_student is not None and per_exam_max is not None \
    and best_student is not None and hardest_exam is not None, \
    "fill in every TODO above before running this check"
assert per_student.shape == (4,), f"per_student should have 4 values, got {per_student.shape}"
assert np.allclose(per_student, [86.33, 75.0, 94.67, 65.67]), f"got {list(per_student)}"
assert list(per_exam_max) == [95, 92, 98], f"got {list(per_exam_max)}"
assert best_student == 2, f"expected student 2, got {best_student}"
assert hardest_exam == 0, f"expected exam 0, got {hardest_exam}"
print("Exercise 7.1 correct.")

Exercise 7.1 correct.


---
# Part 8 · Broadcasting

Arrays of different shapes can often still combine. NumPy stretches the
smaller one to fit — without actually copying the data.

You've used it already: `gpas * 2` broadcasts the single number `2`
across every element.

In [34]:
scores = np.array([
    [88, 92, 79],
    [75, 68, 82],
    [95, 91, 98],
    [60, 72, 65],
])

# One bonus per exam, applied to all students
bonus = np.array([2, 0, 5])          # shape (3,)

print("scores shape:", scores.shape)
print("bonus shape: ", bonus.shape)
print()
print(scores + bonus)

scores shape: (4, 3)
bonus shape:  (3,)

[[ 90  92  84]
 [ 77  68  87]
 [ 97  91 103]
 [ 62  72  70]]


`(4, 3) + (3,)` works: the bonus row is applied to every student.

**The rule:** compare shapes from the right. Dimensions must either
match, or one of them must be 1.

| A | B | Works? |
|---|---|---|
| `(4, 3)` | `(3,)` | yes — applied to each row |
| `(4, 3)` | `(4, 1)` | yes — applied to each column |
| `(4, 3)` | `(4,)` | **no** — 3 vs 4 |

That third case is the one that bites. To apply something per *student*,
reshape it to a column.

In [35]:
per_student_bonus = np.array([1, 2, 0, 3])          # shape (4,)

try:
    scores + per_student_bonus
except ValueError as e:
    print("Error:", e)

print()
column = per_student_bonus.reshape(4, 1)           # shape (4, 1)
print("reshaped to", column.shape)
print(scores + column)

Error: operands could not be broadcast together with shapes (4,3) (4,) 

reshaped to (4, 1)
[[89 93 80]
 [77 70 84]
 [95 91 98]
 [63 75 68]]


### Exercise 8.1
Each exam has a different maximum mark: exam 0 is out of 100, exam 1
out of 100, exam 2 out of 120.

Convert `scores` into **percentages** for each exam, rounded to 1
decimal place. Use broadcasting, not a loop.

In [36]:
max_marks = np.array([100, 100, 120])

percentages = np.round(scores / max_marks * 100, 1)

print(percentages)


[[88.  92.  65.8]
 [75.  68.  68.3]
 [95.  91.  81.7]
 [60.  72.  54.2]]


In [37]:
assert percentages is not None, "percentages is still None"
assert percentages.shape == (4, 3), f"shape should be (4, 3), got {percentages.shape}"
assert np.allclose(percentages[0], [88.0, 92.0, 65.8]), f"row 0 wrong: {list(percentages[0])}"
assert np.allclose(percentages[2], [95.0, 91.0, 81.7]), f"row 2 wrong: {list(percentages[2])}"
print("Exercise 8.1 correct.")

Exercise 8.1 correct.


---
# Part 9 · Reshaping

The same data can be viewed in different shapes, as long as the total
number of elements stays the same.

In [38]:
flat = np.arange(12)
print("flat:  ", flat, flat.shape)
print()
print("3 x 4:")
print(flat.reshape(3, 4))
print()
print("4 x 3:")
print(flat.reshape(4, 3))
print()
print("-1 lets NumPy work it out:")
print(flat.reshape(2, -1).shape, "  (2 rows, columns inferred)")

flat:   [ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)

3 x 4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

4 x 3:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

-1 lets NumPy work it out:
(2, 6)   (2 rows, columns inferred)


`-1` means "figure this dimension out from the others." Handy when you
know you want 2 rows but don't want to count the columns.

Flattening back:

In [39]:
grid = np.arange(6).reshape(2, 3)
print(grid)
print()
print("ravel: ", grid.ravel())       # a view where possible
print("flatten:", grid.flatten())    # always a copy

[[0 1 2]
 [3 4 5]]

ravel:  [0 1 2 3 4 5]
flatten: [0 1 2 3 4 5]


> `ravel()` returns a view when it can, `flatten()` always copies. If
> you plan to modify the result, `flatten()` is the safe choice — for
> the same reason as Part 4.

### Exercise 9.1
`readings_flat` holds 12 sensor readings taken over 4 days, 3 per day,
in order.

- `by_day` — reshaped to 4 rows (one per day), 3 columns
- `daily_mean` — the mean for each day, rounded to 2 decimals

In [40]:
readings_flat = np.array([
    21.0, 22.5, 23.0,
    19.5, 20.0, 21.5,
    25.0, 26.5, 24.0,
    18.0, 17.5, 19.0,
])

by_day = readings_flat.reshape(4, 3)
daily_mean = np.round(by_day.mean(axis=1), 2)

print(by_day)
print(daily_mean)


[[21.  22.5 23. ]
 [19.5 20.  21.5]
 [25.  26.5 24. ]
 [18.  17.5 19. ]]
[22.17 20.33 25.17 18.17]


In [41]:
assert by_day is not None and daily_mean is not None, \
    "fill in every TODO above before running this check"
assert by_day.shape == (4, 3), f"shape should be (4, 3), got {by_day.shape}"
assert np.allclose(by_day[0], [21.0, 22.5, 23.0]), "first day's readings are wrong"
assert np.allclose(daily_mean, [22.17, 20.33, 25.17, 18.17]), f"got {list(daily_mean)}"
print("Exercise 9.1 correct.")

Exercise 9.1 correct.


---
# Part 10 · Matrix operations

`*` multiplies element by element. `@` does matrix multiplication.
They are not the same thing, and mixing them up is a classic bug.

In [42]:
A_mat = np.array([[1, 2],
                  [3, 4]])
B_mat = np.array([[5, 6],
                  [7, 8]])

print("element-wise (A * B):")
print(A_mat * B_mat)
print()
print("matrix product (A @ B):")
print(A_mat @ B_mat)

element-wise (A * B):
[[ 5 12]
 [21 32]]

matrix product (A @ B):
[[19 22]
 [43 50]]


### Transpose

`.T` flips rows and columns.

In [43]:
scores = np.array([
    [88, 92, 79],
    [75, 68, 82],
    [95, 91, 98],
    [60, 72, 65],
])

print("scores.shape:  ", scores.shape)
print("scores.T.shape:", scores.T.shape)
print()
print(scores.T)

scores.shape:   (4, 3)
scores.T.shape: (3, 4)

[[88 75 95 60]
 [92 68 91 72]
 [79 82 98 65]]


### A weighted total

A practical use of `@`: each exam carries a different weight.

In [44]:
weights = np.array([0.25, 0.25, 0.50])     # exam 2 is worth half

final_marks = scores @ weights
print("weights sum to:", weights.sum())
print("final marks:   ", final_marks.round(2))

weights sum to: 1.0
final marks:    [84.5  76.75 95.5  65.5 ]


`(4, 3) @ (3,)` → `(4,)`: one weighted total per student. The inner
dimensions must match — 3 exams against 3 weights.

### Exercise 10.1
Coursework carries 40% and the final exam 60%.

`assessment` holds `[coursework, final]` for each of 5 students.

- `overall` — each student's weighted total, rounded to 2 decimals
- `passed` — the overall marks of students scoring **60 or above**

Use `@` for the weighting.

In [45]:
assessment = np.array([
    [80, 88],
    [65, 55],
    [92, 95],
    [45, 62],
    [70, 58],
])
weights = np.array([0.40, 0.60])

overall = np.round(assessment @ weights, 2)
passed = overall[overall >= 60]

print("overall:", overall)
print("passed: ", passed)


overall: [84.8 59.  93.8 55.2 62.8]
passed:  [84.8 93.8 62.8]


In [46]:
assert overall is not None and passed is not None, \
    "fill in every TODO above before running this check"
assert overall.shape == (5,), f"overall should have 5 values, got {overall.shape}"
assert np.allclose(overall, [84.8, 59.0, 93.8, 55.2, 62.8]), f"got {list(overall)}"
assert np.allclose(passed, [84.8, 93.8, 62.8]), f"got {list(passed)}"
print("Exercise 10.1 correct.")

Exercise 10.1 correct.


---
# Practice what you learned

No new concepts here — everything below uses what's already in this lab.
These are less guided than the exercises above, which is the point.

### The data

A class of 8 students sat 4 assessments. Marks are out of 100.

In [47]:
marks = np.array([
    [78, 82, 91, 68],
    [55, 61, 49, 72],
    [92, 88, 95, 90],
    [43, 58, 51, 62],
    [88, 79, 84, 81],
    [66, 71, 58, 69],
    [95, 97, 93, 99],
    [71, 64, 77, 70],
])

print("shape:", marks.shape, "-> 8 students, 4 assessments")
print(marks)

shape: (8, 4) -> 8 students, 4 assessments
[[78 82 91 68]
 [55 61 49 72]
 [92 88 95 90]
 [43 58 51 62]
 [88 79 84 81]
 [66 71 58 69]
 [95 97 93 99]
 [71 64 77 70]]


### P1 — Assessment difficulty
Which assessment was hardest? Compute `assessment_means` (the mean mark
for each assessment, rounded to 2 decimals) and `hardest` (the index of
the lowest one).

In [48]:
assessment_means = np.round(marks.mean(axis=0), 2)
hardest = assessment_means.argmin()

print(assessment_means, "-> hardest was assessment", hardest)


[73.5  75.   74.75 76.38] -> hardest was assessment 0


In [49]:
assert assessment_means is not None and hardest is not None, \
    "fill in every TODO above before running this check"
assert assessment_means.shape == (4,), f"expected 4 values, got {assessment_means.shape}"
assert np.allclose(assessment_means, [73.5, 75.0, 74.75, 76.38]), f"got {list(assessment_means)}"
assert hardest == 0, f"expected assessment 0, got {hardest}"
print("P1 correct.")

P1 correct.


### P2 — Weighted final mark on the 5.00 scale
The four assessments are weighted 15%, 15%, 30%, 40%.

Compute `final_gpa`: each student's weighted mark converted to the 5.00
GPA scale, rounded to 2 decimals. (A weighted mark of 100 becomes 5.00.)

In [50]:
weights = np.array([0.15, 0.15, 0.30, 0.40])

final_gpa = np.round((marks @ weights) / 100 * 5, 2)

print(final_gpa)


[3.92 3.05 4.58 2.76 4.13 3.28 4.81 3.57]


In [51]:
assert final_gpa is not None, "final_gpa is still None"
assert final_gpa.shape == (8,), f"expected 8 values, got {final_gpa.shape}"
assert np.allclose(final_gpa, [3.92, 3.05, 4.58, 2.76, 4.13, 3.28, 4.81, 3.57]), \
    f"got {list(final_gpa)}"
print("P2 correct.")

P2 correct.


### P3 — Who made the Dean's List?
Using `final_gpa`, compute:
- `dean_count` — how many students reached 4.50
- `dean_indices` — their positions in the class
- `class_average` — the mean GPA, rounded to 2 decimals

In [52]:
dean_count = np.sum(final_gpa >= 4.50)
dean_indices = np.where(final_gpa >= 4.50)[0]
class_average = np.round(final_gpa.mean(), 2)

print("count:  ", dean_count)
print("indices:", dean_indices)
print("average:", class_average)


count:   2
indices: [2 6]
average: 3.76


In [53]:
assert dean_count is not None and dean_indices is not None and class_average is not None, \
    "fill in every TODO above before running this check"
assert dean_count == 2, f"expected 2, got {dean_count}"
assert list(dean_indices) == [2, 6], f"expected [2, 6], got {list(dean_indices)}"
assert abs(class_average - 3.76) < 0.01, f"expected about 3.76, got {class_average}"
print("P3 correct.")

P3 correct.


### P4 — Apply a curve, without damaging the original
Assessment 0 was too hard, so every mark on it gets +5 — capped at 100.

Produce `curved`, a **new** array with the curve applied to column 0
only. `marks` must be completely unchanged afterwards.

This is where Part 4 matters.

In [54]:
curved = marks.copy()
curved[:, 0] = np.where(curved[:, 0] + 5 > 100, 100, curved[:, 0] + 5)

print("curved column 0:", curved[:, 0])
print("marks column 0: ", marks[:, 0], "  <- must be unchanged")


curved column 0: [ 83  60  97  48  93  71 100  76]
marks column 0:  [78 55 92 43 88 66 95 71]   <- must be unchanged


In [55]:
assert curved is not None, "curved is still None"
assert list(marks[:, 0]) == [78, 55, 92, 43, 88, 66, 95, 71], \
    f"marks was modified - it must stay unchanged: {list(marks[:, 0])}"
assert list(curved[:, 0]) == [83, 60, 97, 48, 93, 71, 100, 76], f"got {list(curved[:, 0])}"
assert list(curved[:, 1]) == list(marks[:, 1]), "only column 0 should change"
print("P4 correct - and you kept the original intact.")

P4 correct - and you kept the original intact.


### P5 — Open ended
Using only what's in this lab, answer one question of your own about
this class and print the result. Some starting points:

- Which student was most *inconsistent* across the four assessments?
- Did students who did well on assessment 0 also do well on assessment 3?
- How many students improved from assessment 0 to assessment 3?

Not self-checked — write the code and state your conclusion in a
comment.

In [56]:
# Question: How many students improved from assessment 0 to assessment 3?
improved_mask = marks[:, 3] > marks[:, 0]
improved_count = np.sum(improved_mask)
improved_indices = np.where(improved_mask)[0]

print("Students who improved:", improved_indices)
print("Number who improved:", improved_count)

# Conclusion: 4 students improved; their indices are 1, 3, 5, and 6.


Students who improved: [1 3 5 6]
Number who improved: 4


---
# Before you finish

- [ ] Every self-check cell prints "correct"
- [ ] `numpy` is installed **and** recorded in `requirements.txt`
- [ ] P5 attempted with your own question
- [ ] **Restart Kernel and Run All** — the whole notebook runs with no errors
- [ ] Committed and pushed